### ISSUE TITLE
don't checkout data submodule on github actions

### ISSUE THREAD

**Issue by RussTedrake** [RussTedrake/htmlbook#10]
We're running into memory problems.

I'll need to skip links to the data directory in the html_linktest.  @jamiesnape says "either of the following environment variables CI=true or GITHUB_ACTIONS=true will be set. I check GITHUB_ACTIONS in one of the shell scripts in htmlbook before nuking large numbers of files with sudo ."  so that should work.

And, obviously, to change the submodule checkout step.

**Comment by jamiesnape** [comment]
https://github.com/RussTedrake/htmlbook/blob/c232afe292610836027f3caa084e6546d45ef170/workflows/ci/catalina/setup#L37
